### ISSUE TITLE
Inconsistent Error Messages

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-js#24] opened 2013-08-28 00:30 UTC
balanced.js gives slightly different formats for errors depending on if they are generated via the library or the server.

from the server:

``` json
{
    "status": 404,
    "error": {
        "status": "Not Found",
        "category_code": "not-found",
        "category_type": "request",
        "description": "
The requested URL was not found on the server.

If you entered the URL manually please check your spelling and try again.

 Your request id is OHMc8c72f6a0f7811e39e35026ba7d79bff.",
        "request_id": "OHMc8c72f6a0f7811e39e35026ba7d79bff",
        "status_code": "404"
    }
}
```

from the library

``` json
{
    "error": {
        "card_number": "\"\" is not a valid credit card number",
        "expiration_month": "Missing field",
        "expiration_year": "Missing field",
        "security_code": "\"\" is not a valid credit card security code",
        "expiration": "\"-\" is not a valid credit card expiration date"
    },
    "status": 400
}
```

**Comment by nodesocket** [comment] 2013-09-18 22:22
Duplicate of #38

**Closed as completed by nodesocket** 2013-09-18 22:22 UTC
Labels: bug
