### ISSUE TITLE
Fails to tokenize when '#' is passed into the address line field 

### ISSUE THREAD

**Issue by rserna2010** [balanced/balanced-js#90] opened 2014-03-24 21:50 UTC
http://jsfiddle.net/an5Cz/20/

Throws a 400 error.

**Comment by blim8183** [comment] 2014-03-24 21:52
+1

**Comment by matthewfl** [comment] 2014-03-24 21:53
https://github.com/balanced/balanced-js/blob/rev1/src/balanced.js#L472

I think the issue is that the # isn't being url encoded properly

**Comment by matthewfl** [comment] 2014-03-24 22:10
this should be fixed now, if not please reopen this issue

**Closed as completed by matthewfl** 2014-03-24 22:10 UTC

**Comment by blim8183** [comment] 2014-03-24 22:22
It's working for me now, thanks!
